@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibm9tIjoidGVzdFVzZXIiLCJlbWFpbCI6InRlc1RUVDJAdGVzdC5mciIsImlhdCI6MTc2Mjk1NzQzNSwiZXhwIjoxNzYyOTYxMDM1fQ.Zo95cexuYPUJDdTKMn-MeEfYq2-3Xmjrtf_BrN_k2PA
@baseUrl = http://localhost:3000
≈GET https://encuisine.adrienrossignol.fr/recettes
Content-Type: application/json

### Récupérer la liste des recettes
GET http://localhost:3000/api/recettes
Content-Type: application/json

### Récupérer une recette par son ID
GET http://localhost:3000/api/recettes/1  
Content-Type: application/json

### Enregistrer un nouvel utilisateur
POST http://localhost:4000/api/local/register
Content-Type: application/json

{
  "nom": "testUser",
  "email": "tesTTTT2@test.fr",
  "motdepasse": "testpassword"
}

### Connexion d'un utilisateur
POST http://localhost:3000/api/local/login
Content-Type: application/json

{
  "email": "tesTTT2@test.fr",
  "motdepasse": "testpassword"
}

### Créer une nouvelle recette
POST {{baseUrl}}/api/recettes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "data": {
    "titre": "Recette de test",
    "description": "Ajouter oeufs et lait",
    "difficulte": 15,
    "tempsPrep": 25,
    "budget": 4
  }
}

### créer recette test 1
POST http://localhost:3000/api/recettes
Content-Type: application/json

{
  "data": {
    "titre": "Recette de test 1",
    "description": "Ajouter oeufs et lait",
    "difficulte": 15,
    "tempsPrep": 25,
    "budget": 4
  }
}

### créer recette test 2
POST {{baseUrl}}/api/recettes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "data": {
    "titre": "Recette de test 2",
    "description": "Ajouter oeufs et lait",
    "difficulte": 15,
    "tempsPrep": 25,
    "budget": 4
  }
}

### créer recette test 3
POST {{baseUrl}}/api/recettes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "data": {
    "titre": "Recette de test 3",
    "description": "Ajouter oeufs et lait",
    "difficulte": 15,
    "tempsPrep": 25,
    "budget": 4
  }
}


### créer recette test 4
POST {{baseUrl}}/api/recettes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "data": {
    "titre": "Recette de test 4",
    "description": "Ajouter oeufs et lait",
    "difficulte": 15,
    "tempsPrep": 25,
    "budget": 4
  }
}

### créer recette test 5
POST {{baseUrl}}/api/recettes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "data": {
    "titre": "Recette de test 5",
    "description": "Ajouter oeufs et lait",
    "difficulte": 15,
    "tempsPrep": 25,
    "budget": 4
  }
}

### créer recette test 6
POST {{baseUrl}}/api/recettes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "data": {
    "titre": "Recette de test 6",
    "description": "Ajouter oeufs et lait",
    "difficulte": 15,
    "tempsPrep": 25,
    "budget": 4
  }
}

### Récupérer la liste des recettes
GET {{baseUrl}}/api/recettes
Content-Type: application/json  

### Récupérer une recette par son document ID
GET {{baseUrl}}/api/recettes/q7bzavuvpss2jzog52g0qkfx
Content-Type: application/json

### Mettre à jour une recette
PUT {{baseUrl}}/api/recettes/q7bzavuvpss2jzog52g0qkfx
Content-Type: application/json

{
  "data": {
    "titre": "Recette de test",
    "description": "Ajouter oeufs et lait",
    "difficulte": 15,
    "tempsPrep": 25,
    "budget": 5
  }
}

### Supprimer une recette
DELETE {{baseUrl}}/api/recettes/q7bzavuvpss2jzog52g0qkfx
Content-Type: application/json

### Ajouter des ingrédients à une recette
POST http://localhost:3000/api/recettes/1/ingredients
Content-Type: application/json

{
  "ingredients": [
    { "name": "Farine", "quantite": "200g" },
    { "name": "Sucre", "quantite": "50g" },
    { "name": "Œufs", "quantite": "2" }
  ]
}